---
- name: Install Monit package
  package:
    name: "{{monit_pkg_name}}"
    state: present
    update_cache: yes

- name: Copy pemfile
  copy:
    src: "{{monit_pemfile}}"
    dest: "{{monit_includedir}}/"
    mode: 0600
  notify: Restart_monit.service

- name: Template of os_release.monit.j2
  template:
    src: os_release.monit.j2
    dest: "{{monit_includedir}}/os_release.monit"
    mode: 0644
  vars:
    release_file: "{{monit_os_release_file}}"
  notify: Restart_monit.service

- name: Template of monitrc.j2
  template:
    src: monitrc.j2
    dest: "{{monit_dir}}/monitrc"
    mode: 0600
  vars:
    idfile: "{{monit_idfile}}"
    statefile: "{{monit_statefile}}"
    pemfile: "{{monit_includedir}}/{{monit_pemfile}}"
    includedir: "{{monit_includedir}}"
  notify: Restart_monit.service
