---
- name: Install Monit package
  package:
    name: "{{monit_pkg_name}}"
    state: present
    update_cache: yes

- name: Open the port
  iptables:
    chain: INPUT
    destination_port: "{{monit_port}}"
    action: insert
    jump: ACCEPT
    match: state
    ctstate: NEW
    protocol: tcp
    state: present
  register: port_2812_result
  when: common_iptables != 'disabled'

- name: Save iptables
  shell: "/sbin/iptables-save > /etc/sysconfig/iptables" 
  when: port_2812_result is changed

- name: Copy server.pem
  copy:
    src: server.pem
    dest: "{{monit_includedir}}/"
    mode: 0600
  notify: Restart_monit.service

- name: Template of pemfile
  template:
    src: "{{monit_pemfile}}.j2"
    dest: "{{monit_includedir}}/{{monit_pemfile|basename}}"
    mode: 0600
  vars:
    key_secret: "{{monit_key_secret|replace('\n', '')}}"
  when: monit_pemfile|length > 0
  notify: Restart_monit.service

- name: Template of os_release.monit.j2
  template:
    src: os_release.monit.j2
    dest: "{{monit_includedir}}/os_release.monit"
    mode: 0644
  vars:
    release_file: "{{monit_os_release_file}}"
  notify: Restart_monit.service

- name: Template of monitrc.j2
  template:
    src: monitrc.j2
    dest: "{{monit_dir}}/monitrc"
    mode: 0600
  vars:
    idfile: "{{monit_idfile}}"
    statefile: "{{monit_statefile}}"
    pemfile: "{{monit_includedir}}/{{monit_pemfile|basename|default('server.pem', true)}}"
    user: "{{monit_user}}"
    passwd: "{{monit_passwd|replace('\n', '')}}"
    allow_list: "{{monit_allow_list}} + {{monit_extra_allow_list}}"
    includedir: "{{monit_includedir}}"
  notify: Restart_monit.service
